      PROGRAM DRV
      DOUBLE PRECISION DATE,ALT,COLAT,ELONG,X,Y,Z,F,DX,DY,DZ,DF
      INTEGER IOS
   10 READ(*,*,IOSTAT=IOS) DATE,ALT,COLAT,ELONG
      IF (IOS.NE.0) STOP
      CALL IGRF14SYN(0,DATE,1,ALT,COLAT,ELONG,X,Y,Z,F)
      CALL IGRF14SYN(1,DATE,1,ALT,COLAT,ELONG,DX,DY,DZ,DF)
      WRITE(*,'(4F14.6,8F16.6)') DATE,ALT,90D0-COLAT,ELONG,
     &  X,Y,Z,F,DX,DY,DZ,DF
      GOTO 10
      END
